name: Github CI

on:
  push:
    branches:
      - 'main'

jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: Check Out Repo 
          uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
        - name: Login to Docker Hub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKER_HUB_USERNAME }}
            password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

        - name: Set up Docker Buildx
          id: buildx
          uses: docker/setup-buildx-action@v2

        - name: Build and push gpu image
          id: docker_build_base
          uses: docker/build-push-action@v4
          with:
            context: ./
            file: ./base.dockerfile
            push: true
            tags: ${{ secrets.DOCKER_HUB_USERNAME }}/mxnet-notebook 

        - name: Build and push cpu image
          id: docker_build_cpu
          uses: docker/build-push-action@v4
          with:
            context: ./
            file: ./base-cpu.dockerfile
            push: true
            tags: ${{ secrets.DOCKER_HUB_USERNAME }}/mxnet-notebook-cpu

        - name: Image digest
          run: |
            echo ${{ steps.docker_build_base.outputs.digest }}
            echo ${{ steps.docker_build_cpu.outputs.digest }}
